# Generated by Django 5.0.2 on 2024-03-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=50)),
                ('Car_model', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_year', models.IntegerField()),
                ('control_type', models.CharField(max_length=10)),
                ('mileage', models.IntegerField()),
                ('Car_Color', models.CharField(max_length=10)),
                ('Fuel_Type', models.CharField(default='petrol', max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Cars Info',
                'ordering': ['production_year', '-price'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cars_photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.cars_info')),
            ],
        ),
    ]
