# Generated by Django 5.0.2 on 2024-03-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars_info',
            old_name='Car_model',
            new_name='Car_model_name',
        ),
        migrations.RenameField(
            model_name='cars_info',
            old_name='Car_name',
            new_name='Company_name',
        ),
    ]
