# Generated by Django 5.0.2 on 2024-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_info_body_styel_cars_info_cylinders_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_info',
            name='Cylinders_type',
            field=models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cars_info',
            name='Fuel_Type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Gas', 'Gas'), ('FLEXIBLE FUEL', 'FLEXIBLE FUEL'), ('Electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cars_info',
            name='Keys',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars_info',
            name='control_type',
            field=models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('Manual', 'Manual'), ('steptronic', 'steptronic')], max_length=20),
        ),
    ]
