# Generated by Django 5.0.2 on 2024-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_cars_info_cylinders_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cars_info",
            options={"ordering": ["-price"], "verbose_name_plural": "Cars Info"},
        ),
        migrations.RemoveField(
            model_name="cars_info",
            name="Keys",
        ),
        migrations.RemoveField(
            model_name="cars_info",
            name="Vin",
        ),
        migrations.AddField(
            model_name="cars_info",
            name="car_code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="mileage",
            field=models.CharField(max_length=15),
        ),
    ]
