# Generated by Django 5.0.2 on 2024-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_cars_info_options_remove_cars_info_keys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars_info",
            name="mileage",
            field=models.CharField(max_length=20),
        ),
    ]
