# Generated by Django 5.0.2 on 2024-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_cars_info_mileage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cars_info",
            old_name="Company_name",
            new_name="Make",
        ),
        migrations.RenameField(
            model_name="cars_info",
            old_name="control_type",
            new_name="Transmission",
        ),
        migrations.RemoveField(
            model_name="cars_info",
            name="Vehicle_Type",
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Body_styel",
            field=models.CharField(default="SPORT PI", max_length=30),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Car_Color",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="car_code",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="mileage",
            field=models.CharField(max_length=30),
        ),
    ]
