# Generated by Django 5.0.2 on 2024-03-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_rename_company_name_cars_info_make_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars_info",
            name="car_code",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="price",
            field=models.CharField(max_length=20),
        ),
    ]
