# Generated by Django 5.0.2 on 2024-03-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_alter_cars_info_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carphoto",
            name="photo",
            field=models.ImageField(
                default="cars_photos/DefualtCarPhoto.jpg", upload_to="cars_photos/"
            ),
        ),
    ]
