# Generated by Django 5.0.2 on 2024-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_alter_carphoto_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="num_of_vistors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_of_vistors", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Body_styel",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Car_Color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Car_model_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Cylinders_type",
            field=models.CharField(
                blank=True,
                choices=[("4", "4"), ("6", "6"), ("8", "8")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Drive",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Fuel_Type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petrol", "Petrol"),
                    ("Gas", "Gas"),
                    ("FLEXIBLE FUEL", "FLEXIBLE FUEL"),
                    ("Electric", "Electric"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Make",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="Transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTOMATIC", "AUTOMATIC"),
                    ("Manual", "Manual"),
                    ("steptronic", "steptronic"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="car_code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="engine_capacity",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="mileage",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="price",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="production_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cars_info",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
